### ISSUE TITLE
Does SOCVR handle obviously terrible review audits? 

### ISSUE THREAD

**Issue by rschrieken** [SO-Close-Vote-Reviewers/room-meeting-topics#11]
Bad review audits can be handled by normal users (as in, downvote & VtC or reopen an audit question, so that it ceases to be an audit?).

Do we want the room to be open for such requests and if yes, what would the rules be to govern those requests.

Idea from [Stephen Leppik](https://chat.stackoverflow.com/users/6388243) with as background: https://meta.stackoverflow.com/a/357905/578411

**Comment by NathanOliver1** [comment]
Depending on how you have to deal with it (how to remove it as an audit) it could require down voting.  That goes against our don't ask for votes rule.  This is a pretty small set though and if it is really a bad audit then those votes are needed.  I'm fine with whatever we decide.

**Comment by rschrieken** [comment]
IIRC it needs a single vote to correct a faulty audit. Only wrongly red-flagged posts need moderator intervention. I'm not sure what the room would actually need to add to that. More importantly the *wrong* audits are often contested by the users who fail them and to be honest I don't often find meta posts where the OP is 100% free of blame. So we run the risk of making reviewing easier because we remove the tricky audits. This needs proper discussion and governance if added to the requests we handle, I think. I'm currently not sold on the idea.

**Comment by The-Snide-Sniper** [comment]
I never said SOCVR would handle the "tricky" audits. I was specifically asking about the "obvious" audits. As stated in the linked answer, it's still true that *some* disputed audits are allowed on Meta without being dupe-closed.

**Comment by samliew** [comment]
I'm not keen on broadening the scope of SOCVR specifically for this purpose. This should be more of a developer issue to adjust/tweak the algorithm. Handling poor audits would cause this issue to be less visible to the development team. _(I don't think I can join the meeting due to the timezone difference, so I'll just leave this comment here)_

**Comment by makyen** [comment]
In order for this to be considered, we need to determine what the members of SOCVR *can* do about such audits. If there's nothing we can do beyond what a single user can, then there's no reason to involve the room.

As with @rschrieken, my understanding is that everything that normal users can do about bad audits can be accomplished by a single person:
* For "known-good" posts which normal users can affect: A *single* close- or down-vote will disqualify the post from being considered known-good. 
* For "known-bad" posts which normal users can affect (I'm less sure about the criteria and effects of possible actions on known-bad posts): Most known-bad posts are ones which have been deleted, are highly down-voted, have various flags raised, etc. For those that can be affected by a normal user, my understanding is that a *single* up-, reopen- or undelete-vote will remove it from being known-bad. 


Beyond those single actions, there's nothing that non-moderators can do, AFAIK.

Given that there's nothing multiple users can do beyond what a single user can accomplish, I don't see any reason for SOCVR to get involved, just because there's nothing we can do.

On the other hand, if the user feels the post, independent of being an audit, should be reopened, or undeleted, then posting a `reopen-pls` or `undel-pls` would be quite reasonable.

Some references: [1](https://meta.stackoverflow.com/questions/285702/how-do-review-audits-work-in-triage/285708#285708), [2](https://meta.stackexchange.com/questions/157121/what-are-review-tests-audits-and-how-do-they-work), [3](https://meta.stackoverflow.com/questions/273193/getting-failed-for-review-audits-when-they-are-blatantly-wrong/273194#273194), [4](https://meta.stackoverflow.com/questions/320792/how-is-this-question-a-proper-candidate-for-a-close-vote-audit/320794#320794)
