### ISSUE TITLE
SOCVR Sanitarium needs a better name

### ISSUE THREAD

**Issue by rschrieken** [SO-Close-Vote-Reviewers/room-meeting-topics#17]
The name insinuates illness of anyone who's send there.

That is maybe not the feeling we want to go with that.

This topic is here to seek a new name. 
Design criteria: 
- The name needs un-mistakenly be linked to SOCVR, either by adding the acronym or the verbiage on its own
- The name doesn't need to be in conflict with other rooms, so trash, trash can, trash bin are all ruled out.
- A bit punny is OK but let's not replace it with another derogatory term 

Post and Vote on the suggestions below or  vote on this post, if you feel no change is needed.

One suggestion per comment please!

**Comment by rschrieken** [comment]
'SuperMax'

**Comment by rschrieken** [comment]
'Death Row'

**Comment by rschrieken** [comment]
'Alcatraz'

**Comment by rschrieken** [comment]
'Rikers'

**Comment by rschrieken** [comment]
'JFK'

**Comment by rschrieken** [comment]
Request Treatment Facility?

**Comment by rschrieken** [comment]
Recycling Center

**Comment by rschrieken** [comment]
SOCVR StackDump

**Comment by kingboyk** [comment]
SOCVR Archive

**Comment by honnza** [comment]
SOCVR rev/null

**Comment by Tyler-H** [comment]
SOCVR Archive; most of the rest of these are still offensive. Anything that makes it sound like a jail or a corrective facility should be discarded IMO.

**Comment by makyen** [comment]
SOCVR /dev/null

**Comment by machavity** [comment]
Shoving Other Crazy Votes Room

**Comment by machavity** [comment]
SOCVR Dustbin

**Comment by jotd666** [comment]
SOCVR Black Hole

**Comment by rschrieken** [comment]
SOCVR Oblivion (courtesy of dasblinkenlight)

**Comment by rhexgomez** [comment]
SOCVR Time Capsule

**Comment by vkotovv** [comment]
SOCVR Refurbished

**Comment by vkotovv** [comment]
SOCVR Renovated

**Comment by ferrybig** [comment]
SOCVR Offtopic

**Comment by makyen** [comment]
@Tyler-H Another time, in a situation where people are voting on suggestions in posts, please use a separate message to provide general commentary. Including commentary in the same message as something which we're intended to vote on makes the voting unclear. For example, in this instance, are people upvoting your suggested name or the comment?

**Comment by makyen** [comment]
@Tyler-H  Personally, I would have happily indicated support of the comment, as I agree with it. However, I don't feel the suggested name captures the connotations of the Sanitarium's purpose: a place for our trash (the things we don't want in the room, and which are *not* part of our archive of requests). Thus, I wouldn't pick it as a replacement for "Sanitarium".

OTOH, I think "SOCVR Archive" is a reasonable suggestion to replace the "Graveyard", as that room is our request archive.

**Comment by Tyler-H** [comment]
Frankly I think we should just send our Sanitarium messages to one of the several existing trash chat rooms. I don't see any virtue in maintaining our own 'trash' room, especially considering there are links to the both the source and the destination regardless of which room you send a message to. I can't recall a time where we have needed to move a message *back* from the Sanitarium to the SOCVR room, which would be one of the very few reasons to maintain our own room.

**Comment by gunr2171** [comment]
The primary advantage of maintaining our own trash room is to control the room owner list of that room. This gives us two important abilities

1. We can moved messages back to SOCVR  or another room if needed
2. We can see deleted messages. We do keep tabs on conversations that get out of hand, and being able to see deleted messages helps us gather evidence and learn more about the situation. 

Now, these abilities don't get used much, but as an RO I'd want them available when needed.

**Comment by makyen** [comment]
@Tyler-H To the best of my knowledge, there's no easy way to determine what has been moved in any particular historical move event,<sup>1</sup> nor is it easily possible to find all the messages which were moved out of a particular room, if they are intermingled with messages moved from other rooms.

You can obtain movement information on a single question by single question basis from each individual question's history. Doing so takes an AJAX request per question, which is, probably, subject to rate limits. In addition, the tools don't exist to do so in a way that would be helpful for searching, or recovering what the full history of the room would be, if it would be necessary to comb though a room where SOCVR's messages are mixed with messages from other rooms. With a separate room which is just for messages moved out of SOCVR, it is possible to reconstruct the full history with relative ease.

While it hasn't happened often, we have had occasion to move messages back into SOCVR from the Sanitarium. You need to be a Room Owner in order to move a message out of a room.

@gunr2171 has mentioned another important point, which is that being an RO of the room allows us to look at the content of deleted messages, which we do when appropriate/needed.

The Room Ownership issues are potentially solvable if a shared trash room is used. However, the history recovery issues are not easily solvable, without development work from SE, which is unlikely.

----
1. The Archiver works around this by remembering the messages moved by the individual RO and allows them a limited undo-move capability, but that is only for the most recent move by that RO.

**Comment by Tyler-H** [comment]
@gunr2171 As I said I don't recall this having ever been used. Obviously you don't declare to the SOCVR room when you do it, but I assume the Sanitarium ROs are the same as the SOCVR room... so you can see the deleted messages before they are moved, no? Anything that's so important to be seen after deletion is probably something more appropriate for a moderator to be aware of, anyway. 

As a room owner of several years myself, I still don't see any virtue in having a special room for this, or that things moved there erroneously are really so important that they *need* to be moved back; chat is roughly on par with SO main comments, WRT transience. 

But yes it'd be nice if there were per-room recycling bins where ROs could determine read access.

**Comment by GertArnold** [comment]
SOCVR Sidetrack

**Comment by maskedcoder** [comment]
SOCVR Closet

**Comment by maskedcoder** [comment]
SOCVR's Other Room

**Comment by maskedcoder** [comment]
SOCVR Woodshed

**Comment by maskedcoder** [comment]
SOCVR [Nexus](http://memory-alpha.wikia.com/wiki/Nexus)

**Comment by maskedcoder** [comment]
SOCVR Underground

**Comment by maskedcoder** [comment]
SOCVR's Hidden Kingdom
