### ISSUE TITLE
Do we need *Do not request action on a post that you have asked or answered, or for an edit which you have made*

### ISSUE THREAD

**Issue by NathanOliver1** [SO-Close-Vote-Reviewers/room-meeting-topics#18]
Is this really useful?  Is it helping?  Can we not have this rule and just use common sense?  When new users come in and ask to reopen a post they have a stake in they violate the rule but we allow it (at least I do because if it really needs to be handled we should help).

**Comment by Tyler-H** [comment]
The rule was put in place to prevent people from abusing the system - answering and then getting a question closed as a dupe or off-topic, but still having their answer there to garner points or attention. If it is problematic in it's current iteration, I would recommend just simplifying it to "Do not request closure on a post that you have asked or answered, unless you are unable to delete it yourself due to system restrictions".

This will allow people to ask for actions on questions they asked or answered but are unable to handle themselves (multiple people have answered their question, or the answer they posted has been accepted, etc.).

**Comment by makyen** [comment]
Unfortunately, common sense is not common.

The rule exists both to stop abuse, and also to prevent the *appearance* of SOCVR being a voting ring, where users, particularly regulars, can come to have actions taken which they can't accomplish themselves, on posts in which they are involved. These are good reasons. Without the rule, there *will be* abuse.

So, personally, I prefer that the rule remain, in one form or another.

OTOH, if there is a (rare) situation where the ROs who happen to be present decide that they are not going to enforce the rule, then that's up to them. (The other ROs can discuss with them why that choice was made).

**Comment by makyen** [comment]
If we feel that we should modify the rule, we could also discuss that.

For example, we might want to permit `reopen-pls` requests for question's you've answered. IME, that is the most common situation where there is significant objection to this rule. It's also the situation where there's the least personal benefit to the requester.

**Comment by makyen** [comment]
Related prior Room meeting discussion:

* [November 2017](https://socvr.org/room-info/room-meetings/2017-11): 6. [Should people be allowed to post approve-pls requests for their own tag-wiki suggested edits which remove plagiarism?](http://chat.stackoverflow.com/rooms/108179/conversation/2017-november-topic-6)
  * "the decision is to disallow it for now but remain open to the subject being revisited in the future when/if there is more info available from mods/employees. We ask Meta as well"
