### ISSUE TITLE
Should we wait until after the grace period is over before posting a cv-pls request?

### ISSUE THREAD

**Issue by dadkool** [SO-Close-Vote-Reviewers/room-meeting-topics#19]
Is there a rule/guideline for how long we should wait before posting a cv-pls request?

 Maybe like wait until the 5 min grace period is over?

**Comment by Tyler-H** [comment]
There is no guide currently. It would be hard to enforce because some questions are going to be off-topic no matter how long we wait or how many edits the person makes. In an ideal world we would implement a rule like this and it would only apply to close reasons such as "No MCVE" or "Too Broad" or "Unclear" but none of the other ones. I would be for this rule in those cases, but not in cases where the question is off-topic, a duplicate, etc.
