### ISSUE TITLE
Should users be allowed to request action on posts they are involved in?

### ISSUE THREAD

**Issue by mason-mcglothlin** [SO-Close-Vote-Reviewers/room-meeting-topics#23]
No 15 on the FAQ states "Do not request action on posts or edits where you are involved or where you have a conflict of interest." I disagree with this rule.

After some discussions in the chat room, I came away with two possible intentions for this rule:

1. Prevent the situation where a user might answer a question, then convince other people to close the question for some reason, thus ensuring no one else can answer.

2. Prevent there from being the appearance of some sort of favoritism by SOCVR members on behalf of one of the users participating in a post.

If I have unfairly stated those reasons, feel free to let me know. I don't agree with them, which is why I have such a hard time getting myself to see things from that viewpoint and give it a fair description.

Now, to dispute those points. I disagree with No 1, because that can happen anyways. How hard would it be for someone to gain the 20pts required to participate in a chat room? So someone could create a separate account, use it to make requests in SOCVR that work in their behavior. Or they could ask a friend to request for them. So this rule that SOCVR in actuality does not prevent the thing it's intended to prevent. It just barely mitigates it at all. What's a better way to fight against this sort of behavior? I typically downvote answers on questions that are clearly off-topic, even if the answer contains otherwise useful information. This teaches people that they should consider the rules before answering, and keeps them from being rewarded for rewarding others in breaking the rules. This is getting away from the point of SOCVR, but my point is that it shouldn't be on SOCVR to worry about these issues.

I disagree with No 2, because it's just silly. Users can and often do complain when their question is closed anyways, even if the person that requested action didn't have prior involvement in a post. As users entrusted with moderation privileges, it is our duty/right to use all the tools at our disposal to help keep the content of the site clean. If you are presented with bad content, then you should clean it up, regardless of how it came to your attention. The primary focus of those participating as moderators should be on the content. Even if someone does something for personal revenge or other nefarious motivations, those actions are almost never unilateral and still require the ascent of multiple other users who have been entrusted with moderation privileges.

If someone does raise a complaint, then the CM team or elected moderators can look into the issue and decide whether the appropriate action was taken. If there's a repeat history of a user abusing their moderation privileges for personal reasons, then they can take appropriate action.

My Stack Overflow username is [mason](https://stackoverflow.com/users/1139830/mason) on Stack Overflow. Not sure if you need to know that for some reason. I'm unaccustomed to participating in SOCVR besides occasionally popping in to make a request (and jumping on some of the relevant requests I see).

**Comment by kingboyk** [comment]
If you're proposing the removal of the rule in its entirety I think that would be a very hard sell indeed.

Did you not want to restrict discussion to the scenario where a good answer is being lost due to an OP deleting their question?

**Comment by mason-mcglothlin** [comment]
No, I don't want to restrict the discussion to that. I think the rule is completely useless as it is, and just prevents good people from doing good work. If you feel like you can't take moderation steps for the fear that the mere appearance of acting biased is going to get you in trouble, then it's a sad day indeed for Stack  Overflow.

**Comment by Tyler-H** [comment]
>  I disagree with No 1, because that can happen anyways.

The argument that we shouldn't enforce a rule because it can be circumvented is a very weak argument; by the same logic, states should not outlaw things like murder because they will happen anyway. If a user wants to engage in voter fraud to circumvent one of our room rules, that's on them, and honestly is more of a plus point for having the rule rather than for discarding it.

> Prevent there from being the appearance of some sort of favoritism by SOCVR members on behalf of one of the users participating in a post.

This is not exactly a reason for the rule. I will, however, point out that SOCVR's rules are crafted to keep us in the most transparent and reasonable light of Meta and the moderators/CMs, as we are essentially a voting ring, albeit one with strictly-controlled mandate. At any point, Shog or another CM could drop by and say "yeah I've changed my mind; SOCVR is not allowed anymore" and the room would have to be closed. So to your point, yes, our rules are crafted to avoid any kind of 'favoritism' or *undue* influence that normally a user cannot achieve on their own. 

The SOCVR group/chatroom has been poked and prodded under a microscope on Meta.SE in an unfriendly manner a number of times, and our rules are tailored in response to those criticisms as best they can be. Just like a curling iron might have the warning label "do not stick this in any bodily orifice", our rules are all there *for a reason*. It may be a one-off or a silly reason, but it's still a reason.

Because we are a tacitly-approved voting ring, the potential for abuse is quite high. Thus, these rules are likely to stick around unless some stronger reasoning is presented beyond "this is silly". I'll leave the issue open for a current RO to respond to or add to a list of topics to revisit during our next room meeting, but don't expect this to change with the reasoning you've provided.

**Comment by mason-mcglothlin** [comment]
Sure, at any point someone can drop by and say SOCVR isn't allowed on Stack Overflow. But all that really means is you're not allowed to use chat. You can still have a voting ring, and there's really not much anyone can do about it.

A voting ring with the intention of enforcing the rules is really just effective, organized moderation. There's nothing wrong with that. You're so worried about the appearance of doing something wrong that you put these ridiculous rules in place. You say they're for a reason, but the reasoning isn't valid.

I don't care if you're put under a microscope on Meta. Nor should you. Just ask yourself when you take any moderation: is this action the correct one to take? If you can be reasonably confident in that, you shouldn't fear any backlash from another group for it. Because if you do get in trouble for making a good faith moderation attempt, then that shows the problem is with whoever is scrutinizing you, not your own action.

As you can probably guess, I wasn't aware of this rule and ran afoul of it. There was a question on the site, and I answered it. The user edited their post to say the question was no longer necessary because they decided to take a different approach. I felt the question itself was a legitimate question that had actual value, and I didn't want their question and my answer to be lost. Knowing that the only viable way to get it un-deleted (without bothering an elected mod) was to bring it in front of enough people to get it undeleted, I chose to post in SOCVR chat. I made my request, and disclosed that I had been involved in the question.

My request was deleted for violating rule No 15. Funnily enough, the proper outcome happened: by bringing it to SOCVR's attention, enough people saw it that we successfully undeleted the question. If you ask me, that was indeed the proper outcome. But were I follow rule No 15 in the future, we won't be able to get that proper outcome. Good content will be lost. All because the people that make the rules for SOCVR are afraid of the *appearance* of doing the wrong thing, and less concerned with actually preserving good content. That's not to say they don't care about good content (I really do appreciate everyone's contributions!), just that it's not as high a priority as maintaining a good image and avoiding controversy. Which to me, is kind of sad.

If I'm presented with this situation again in the future, I don't know that I will follow rule No 15. Because I care about the quality of content on Stack Overflow more than I care about the image of a chat room. When I come to SOCVR and make a request, it is not an order for you to go and carry out my request. It's merely a request, and I fully expect you to use your best judgement when deciding what action to take on any given post, regardless of who requested what. So long as you do that, you really have nothing to fear from anyone else.

**Comment by Tyler-H** [comment]
> Sure, at any point someone can drop by and say SOCVR isn't allowed on Stack Overflow. But all that really means is you're not allowed to use chat. You can still have a voting ring, and there's really not much anyone can do about it.

Actually, no, we can't. If CMs or moderators tell you to stop doing something, and then you keep doing it, that's going to get you banned. It's not the fact that we have a chatroom that is on tenterhooks, but that we are a voting ring. Doesn't matter whether we coordinate on SO or in Slack or via carrier pigeons. 

> You're so worried about the appearance of doing something wrong that you put these ridiculous rules in place. You say they're for a reason, but the reasoning isn't valid.

> I don't care if you're put under a microscope on Meta. Nor should you. Just ask yourself when you take any moderation: is this action the correct one to take? If you can be reasonably confident in that, you shouldn't fear any backlash from another group for it. Because if you do get in trouble for making a good faith moderation attempt, then that shows the problem is with whoever is scrutinizing you, not your own action.

It doesn't really matter if you think the reason is valid or not; we have lived through not having them, getting called out (and in fact have even been told at times we are [doing things wrong](https://meta.stackoverflow.com/questions/307009/clean-up-by-downvoting-a-ridiculous-user-experience)), and adjusted our rules to adapt, often with quite heavy input from moderators and Shog. 

> If I'm presented with this situation again in the future, I don't know that I will follow rule No 15

If you don't want to abide by SOCVR rules, that's fine, but be prepared to have your requests binned by ROs and also be prepared to be kicked from the room if you continue to violate them. Since it seems you're more interested in calling the rule stupid than discussing its merits or its implementation details, I'll go ahead and close this.

**Comment by mason-mcglothlin** [comment]
I didn't say that you just keep on doing things you're told not to do. You missed my point: you're not going to be told to stop moderating content as long as you are operating within the rules, curating good content.

The question you linked to is a perfect example of that. It's not the fact that things were organized: it's the fact that poor moderation choices were made.

It's not that I don't want to abide by the SOCVR rules, but that I'm only going to abide by them so long as they make sense and actually serve a valuable purpose. And I haven't seen any convincing argument that they serve a valuable purpose. Clearly this isn't a situation that happens often. Out of my seven years on SO, I can probably count on one hand the number of times I answered on a valuable question and then the question got deleted. But when it does happen, I want to know that I can come to other people who are interested in promoting quality content and get it restored if they agree it's worth saving. That's why I came here, and I do not understand why you've chosen to unilaterally close my meeting request.

**Comment by machavity** [comment]
> If you feel like you can't take moderation steps for the fear that the mere appearance of acting biased is going to get you in trouble, then it's a sad day indeed for Stack Overflow.

I think you're forgetting two important points

1. The room is scrutinized on meta, not the other way around. ([Rule 25](https://socvr.org/faq#GEfM-dont-jump-bandwagon))
2. There's people on Meta who want us shut down.

SOCVR **must** aim for being beyond reproach or there are people who, if given the opportunity, can and will make a torch-and-pitchfork mob on Meta and shut us down. Believe me, the ROs have to keep a loose eye on Meta because those people can and do make their presence and displeasure known on a regular basis. You might find this rule to be restrictive, but it's necessary for us to keep doing what we do. So, no, we don't allow even the appearance of impropriety. That's not going to change.

**Comment by mason-mcglothlin** [comment]
I'm not forgetting those points. I'm just saying they don't make sense.

Sure the room is scrutinized on Meta. Every moderator action is scrutinized on Meta. If we let the fact that we're scrutinized on Meta stop us from curating content effectively, then the site's quality is going to plummet. SOCVR is scrutinized not because SOCVR is wrong, but because people don't like having their content curated. They don't like being told "you can't ask this question here". Regardless of whether SOCVR is involved or not. SOCVR is a tool to get content in front of the eyes of people with moderation privileges so that quick action can be taken when necessary. So it makes sense people are going to scrutinize it, but that scrutiny isn't a bad thing. We shouldn't avoid action just because someone might take offense at it and decide to complain.

Again: it appears to me you're worried more about the appearance of being wrong than actually being wrong. Calling back to the original reason that prompted me to come here, a legitimate question was deleted by the asker. I had already answered the question. I felt like both the question and my answer could be of use to people in the future. Knowing that the smoothest path to getting it un-deleted was to bring it in front of SOCVR, that's what I did. I even made sure to disclose that I had direct involvement in the post. *Why shouldn't that be allowed on SOCVR?* If you were to go back and read the question, you'd probably agree (as two others did) that the question was worth saving. If I hadn't had direct involvement in the question and had asked others to undelete it, then we wouldn't have this controversy, right? So why should my direct involvement matter? We're supposed to moderate the content, not the people. By preventing me from requesting that others take a look at the question for possible action, aren't we moderating the person rather than the content?
