### ISSUE TITLE
Should SOCVR encourage cleanup of canonical questions?

### ISSUE THREAD

**Issue by jdd-software** [SO-Close-Vote-Reviewers/room-meeting-topics#26]
Should SOCVR actively encourage clean-up (delete bad answers) of canonical questions?

If so how?

Keep a list for 20k, userscript with special tag?

<sup>This is inspired from TylerH's meta, https://meta.stackoverflow.com/q/380811/5292302</sup>

**Comment by Tyler-H** [comment]
Problematic things this would entail if we voted in favor of it (not an exhaustive list):

- Allowing an exception to the rule of posting *-pls requests for posts that are not recently active.
- Allowing *-pls requests that imply or require downvotes as well as the requested *-pls action in the event that answers are positively scored

**Comment by machavity** [comment]
I'd be more inclined to leave this up to individuals to [del-pls] the answers that need to go away, as opposed to trying to proactively "clean up" a canonical like we clean up tags. Unlike questions, answers can be trickier because there might be half a dozen valid ways to put an answer (and people LOVE to restate existing solutions because "this worked for me"). This tends to need a domain specific knowledge
