### ISSUE TITLE
What should be done with cv-pls requests from <3k users?

### ISSUE THREAD

**Issue by gparyani** [SO-Close-Vote-Reviewers/room-meeting-topics#31]
The FAQ says that 3k+ users should vote to close five other questions for every request they file, and that <3k users should "refrain" from filing such requests (since they can't give back as they don't have enough rep). However, I've often seen (from personal experience) that certain requests from <3k users are *de facto* accepted within limits.

Since there is no explicit, enforced policy with regards to <3k+ rep users filing such requests, should we officially codify one? Should it be altogether disallowed, or should it be allowed but with explicit limits (e.g. no more than two at a time, can only file if it's disputed or about to be disputed in Triage, can file if there was a bot report, etc.)?

Also, what about [del-pls] requests?

**Comment by makyen** [comment]
The current rule regarding this is:

> [To make sure people don't abuse the system, requests for actions which you can not perform should be kept to a minimum.](https://socvr.org/faq#can-i-request-people-to-vote-or-flag-on-posts-i-find)

The rule is intentionally vague as to specific limits. This allows users to participate, to an extent, prior to having the ability to actually cast the type of vote requested. The intent is to make enforcing this a judgement call by the ROs based on the requests the user posts (e.g. volume of requests, value of the requests to the site, how closely they are following other rules, etc.)

**Comment by gparyani** [comment]
@makyen How about setting some basic guidelines or guideline examples, such as the examples I gave above?

**Comment by gparyani** [comment]
@rschrieken Why was this marked deferred?

**Comment by codygray** [comment]
> Since there is no explicit, enforced policy with regards to <3k+ rep users filing such requests, should we officially codify one?

No. There is no advantage to be gained from setting an explicit policy surrounding this.

As @makyen already said, the current rule was intentionally left vague to allow room owners to enforce as they see fit using their own judgment. Codifying it into a policy will lose the judgment aspect, which is really essential. All of the relevant factors cannot possibly be put into a policy, and if they somehow were shoehorned in, the policy would be miles long. That doesn't benefit anyone.

> Should it be altogether disallowed&hellip;?

No, definitely not. <3k+ rep users should be allowed to participate. They come across garbage, too, after all, and they are arguably in even greater need of an outlet to get it removed.

> &hellip;should it be allowed but with explicit limits (e.g. no more than two at a time, can only file if it's disputed or about to be disputed in Triage, can file if there was a bot report, etc.)?

The operative rule is and should continue to be the summary for rule 12:

> [Limit the number of requests you make, particularly `cv-pls` requests, to "reasonable" numbers and rates of posting. The exact limits are *not specified*.](https://socvr.org/faq#GEfM-limit-your-requests)

We got into this problem by being too specific *already*. The rule is to limit your requests to reasonable numbers and rates. Room owners can determine reasonability per their own judgment, and they are expected to warn someone when they are getting close to exceeding what is reasonable so that they can modify their behavior accordingly.
