### ISSUE TITLE
Remove/replace misleading example for custom close reasons

### ISSUE THREAD

**Issue by codygray** [SO-Close-Vote-Reviewers/room-meeting-topics#36]
In the [What Should Request Reasons Contain?](https://socvr.org/faq#what-should-request-reasons-contain) section of the FAQ, it says the following:

> For `cv-pls` requests: As with most requests, a request reason is required. **It is *highly recommended* that your request reason includes your actual close reason**, even if that was a custom reason (e.g. "Custom: Homework without attempt"). Including an actual close reason significantly increases the likelihood that your request will be acted upon by other users. A request reason of just "off-topic" is insufficient, because it leaves too many possibilities as to why you feel the question should be closed.

This is great advice, but the example is bad. "Homework without attempt" is **not** a valid close reason, and therefore should not be given in the official FAQ as an example. This example should either be replaced or removed (if we cannot agree on a suitable replacement).

As a replacement, consider: "Custom: SEO question unrelated to programming" or "Custom: customer support request for a third-party service".

**This needs to happen sooner, rather than later!**

**Comment by Tyler-H** [comment]
It's probably worth pointing out that specific reason was edited out of the Help Center page by @codygray alone, but was re-added by @makyen later; I believe Makyen said he would talk about it with Cody, but perhaps that hasn't happened or the outcome wasn't discussed publicly. AFAIR the Meta consensus was that homework attempts do indeed need to show an attempt at answering to be on-topic. At the time the subject was first broached in the SOCVR chatroom, I mentioned I would need to check Meta for discussions on the subject to recall for sure. I haven't done that yet. Adding Makyen for review re: the prior discussion/changes.

**Comment by Tyler-H** [comment]
The nature of the request seems to be about removing an example custom close reason you think is not a valid close reason. My response pointed out that current consensus on the site is that it *is* a valid close reason.

Regarding Help Center citations, all of SOCVR's operations in general rely on the Help Center and relevant Meta consensus, whether we directly cite them as justification anywhere or not. The [Help Center states](https://stackoverflow.com/help/on-topic):

> Questions asking for homework help are not inherently off-topic. **However, you must have made a good faith attempt to solve it yourself.**

(emphasis mine). This has been the case since at least [2014](https://meta.stackoverflow.com/a/253793/2756409). The [Meta FAQ](https://meta.stackoverflow.com/questions/334822/how-do-i-ask-and-answer-homework-questions) on the subject also includes the following guidance at multiple points:

> Make a good faith attempt to solve the problem yourself first.

and

> Ask about *specific* problems with your *existing* implementation.

Now... if you just want a different example to be given, that's probably not a big deal, but I think it's important to address what I see as a moderator trying to change years of precedent unilaterally (by basing arguments on the claim that "homework without an attempt" is not a valid close reason); that, to me, is what's not really fair, because the outcome of the request above is not just that the example changes, it's also that people stop close voting homework questions that don't show an attempt. Whether such close voting should or should not be happening is outside the purview of SOCVR--it's a site-wide decision to make, because such implications will invariably ripple outward. 

Likewise if you think SOCVR just shouldn't allow requests for homework attempts without an effort given already (since we are more restrictive than organic activity on the site already in many ways), that's fine to propose too (as a separate topic or as a major replacement of this one, which would then necessitate the changing of the example).

**Comment by makyen** [comment]
Resolved with [f63d15b](https://github.com/SO-Close-Vote-Reviewers/socvr-website-content/commit/f63d15bc1be560a996bfa316e928ce0c003a3f5b).
